
#Owner Routes

###
GET http://localhost:3000/owners
###
GET http://localhost:3000/owners/1
###
POST http://localhost:3000/owners/create
Content-Type: application/json

{
  "name":"Arun"
}

#Fleet Routes 

###
GET http://localhost:3000/fleets
###
GET http://localhost:3000/fleets/10
###
POST http://localhost:3000/fleets/create
Content-Type: application/json

{
  "fleetType":"Corporate",
  "ownerId": 4
}

#Vehicle Routes

###
GET http://localhost:3000/vehicles
###
GET http://localhost:3000/vehicles/12345
###
POST http://localhost:3000/vehicles/create
Content-Type: application/json

{
  "vin":12345,
  "manufacturer":"Hyundai",
  "model":"Cresta",
  "fleetId": 5,
  "registrationStatus":"Active"
}

###
DELETE http://localhost:3000/vehicles/delete/12345

#Telemetry

###
GET http://localhost:3000/telemetry
###
GET http://localhost:3000/telemetry/history/123146
###
GET http://localhost:3000/telemetry/latest/12345
###
POST http://localhost:3000/telemetry/create
Content-Type: application/json

{
  "vin": 123145,
  "latitude": 37.7749,
  "longitude": -122.4194,
  "speed": 60,
  "fuelLevel": 80,
  "engineStatus": "On",
  "odometerReading": 150,
  "timestamp": "2023-10-05T12:00:00Z"
  
}

###
POST http://localhost:3000/telemetry/bulk
Content-Type: application/json

[
  {
    "vin": 123145,
    "latitude": 37.7749,
    "longitude": -122.4194,
    "speed": 60,
    "fuelLevel": 80,
    "engineStatus": "On",
    "odometerReading": 150,
    "timestamp": "2023-10-05T12:00:00Z"
  },
  {
    "vin": 123146,
    "latitude": 37.7749,
    "longitude": -122.4194,
    "speed": 60,
    "fuelLevel": 80,
    "engineStatus": "On",
    "odometerReading": 150,
    "timestamp": "2023-10-05T12:00:00Z"
  },
  {
    "vin": 123147,
    "latitude": 37.7749,
    "longitude": -122.4194,
    "speed": 60,
    "fuelLevel": 80,
    "engineStatus": "On",
    "odometerReading": 150,
    "timestamp": "2023-10-05T12:00:00Z"
  }
]