
#Owner Routes

###
GET http://localhost:3000/owners
###
GET http://localhost:3000/owners/1
###
POST http://localhost:3000/owners/create
Content-Type: application/json

{
  "name":"Arun"
}

#Fleet Routes 

###
GET http://localhost:3000/fleets
###
GET http://localhost:3000/fleets/10
###
POST http://localhost:3000/fleets/create
Content-Type: application/json

{
  "fleetType":"Corporate",
  "ownerId": 4
}

#Vehicle Routes

###
GET http://localhost:3000/vehicles
###
GET http://localhost:3000/vehicles/12345
###
POST http://localhost:3000/vehicles/create
Content-Type: application/json

{
  "vin":12345,
  "manufacturer":"Toyota",
  "model":"Camry",
  "fleetId": 5,
  "registrationStatus":"Active"
}

###
DELETE http://localhost:3000/vehicles/delete/12345
